apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  labels:
    app.kubernetes.io/name: college-control-system
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: college-control-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
