apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: college-control-system
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: college-control-system
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/component: api
