apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  labels:
    app.kubernetes.io/name: college-control-system
    app.kubernetes.io/component: loki
    app.kubernetes.io/part-of: college-control-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
