apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: college-control-system
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: college-control-system
spec:
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  selector:
    app.kubernetes.io/component: prometheus
