apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: college-control-system
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: college-control-system
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app.kubernetes.io/component: grafana
