apiVersion: v1
kind: Secret
metadata:
  name: college-secrets
  namespace: college-system
  labels:
    app.kubernetes.io/name: college-control-system
    app.kubernetes.io/part-of: college-control-system
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: ""

  # Connection Strings
  ConnectionStrings__DefaultConnection: ""

  # JWT
  JWT__Issuer: ""
  JWT__Audience: ""
  JWT__SecretKey: ""
  JWT__ExpireAfterInMinute: ""

  # ImageKit
  ImageKitOptions__PublicKey: ""
  ImageKitOptions__PrivateKey: ""
  ImageKitOptions__UrlEndpoint: ""

  # Brevo (Email)
  Brevo__ApiKey: ""
  Brevo__SenderEmail: ""
  Brevo__SenderName: ""

  # Admin Account
  AdminAccount__Email: ""
  AdminAccount__Password: ""
  AdminAccount__PhoneNumber: ""
  AdminAccount__UserName: ""
